CREATE TABLE COMMENTS (
   ID VARCHAR(255) NOT NULL PRIMARY KEY,
   TEXT VARCHAR(500) NOT NULL,
   MODIFIED_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
   GAME_ID BIGINT NOT NULL
);

CREATE INDEX comments_game_id ON comments (game_id);
